name: Lint Shell Scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          scandir: .          # Analyse tous les scripts dans ton repo
          severity: warning   # Niveau de sévérité (info, warning, error)
