name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Vérifie les scripts Shell avec ShellCheck
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v1.1.0

      # Petit test pour montrer que ça marche
      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
