name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Installe ShellCheck
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # Lance ShellCheck sur tous les fichiers .sh
      - name: Run ShellCheck
        run: shellcheck **/*.sh || true

      # Petit test pour la vitrine
      - name: Say Hello
        run: echo "✅ Workflow executed successfully"
