name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # Analyse tous les .sh (sans masquer les erreurs)
      - name: Run ShellCheck on *.sh
        run: |
          set -euo pipefail
          # Trouve tous les .sh puis lance shellcheck; ne fait rien s'il n'y en a pas
          mapfile -d '' files < <(find . -type f -name '*.sh' -print0)
          if (( ${#files[@]} )); then
            shellcheck -x "${files[@]}"
          else
            echo "No .sh files found"
          fi
